repos:
  # Code formatter (Black)
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.11

  # Linting (ruff)
  - repo: local
    hooks:
      - id: run-ruff
        name: Run ruff lint
        entry: ruff check
        language: system
        types_or: [python, pyi]
        stages: [pre-commit]

  # Pre-commit housekeeping
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ".*(\\.idea/workspace\\.xml|config\\.yaml)$"

  # Linting (flake8)
  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        args:
          - "--max-line-length=120"
          - "--ignore=E231, F403, F401"
